name: macOS release (binary)

on:
    release:
        types: [published]

env:
    CARGO_TERM_COLOR: always
    LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
    LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}

jobs:
    build:
        strategy:
            matrix:
                os: [macos-15, macos-15-intel]

        runs-on: ${{ matrix.os }}

        env:
            ARCH: "${{ endsWith(matrix.os, 'intel') && 'intel' || 'arm' }}"

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
            - name: Install minisign
              run: brew install minisign
            - name: Update rust
              run: rustup update
            - name: Set ENV
              run: echo "TARGET_TRIPLE=$(rustc -vV | grep 'host:' | cut -d' ' -f2)" >> $GITHUB_ENV
            - name: Install cntp build tools
              run: |
                  cargo install --git https://github.com/vicr123/contemporary-rs.git cargo-cntp-bundle
                  cargo install --git https://github.com/vicr123/contemporary-rs.git cargo-cntp-deploy
            - name: Build
              run: cargo build --verbose --profile release-distro
            - name: Bundle
              run: cargo cntp-bundle --no-open --verbose --profile release-distro
            # Codesigning adapted from https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using-github-actions/
            - name: Codesign app bundle
              env:
                  MACOS_CERTIFICATE: ${{ secrets.PROD_MACOS_CERTIFICATE }}
                  MACOS_CERTIFICATE_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
                  MACOS_CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}
                  MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
              run: |
                  echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
                  security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
                  security default-keychain -s build.keychain
                  security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
                  security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
                  security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain
                  /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_NAME" --options runtime target/bundle/${{ env.TARGET_TRIPLE }}/release-distro/Hummingbird.app -v
            - name: "Notarize app bundle"
              env:
                  PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
                  PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
                  PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
              run: |
                  echo "Create keychain profile"
                  xcrun notarytool store-credentials "notarytool-profile" --apple-id "$PROD_MACOS_NOTARIZATION_APPLE_ID" --team-id "$PROD_MACOS_NOTARIZATION_TEAM_ID" --password "$PROD_MACOS_NOTARIZATION_PWD"
                  echo "Creating temp notarization archive"
                  ditto -c -k --keepParent "target/bundle/${{ env.TARGET_TRIPLE }}/release-distro/Hummingbird.app" "notarization.zip"
                  echo "Notarize app"
                  xcrun notarytool submit "notarization.zip" --keychain-profile "notarytool-profile" --wait
                  echo "Attach staple"
                  xcrun stapler staple "target/bundle/${{ env.TARGET_TRIPLE }}/release-distro/Hummingbird.app"
            - name: Make DMG
              run: cargo cntp-deploy --no-open --verbose --output-file "hummingbird-$ARCH.dmg" --profile release-distro
            - name: Make Zip
              run: |
                  cd target/bundle/${{ env.TARGET_TRIPLE }}/release-distro
                  zip -r "$GITHUB_WORKSPACE/hummingbird-$ARCH.zip" Hummingbird.app
            - name: Prepare minisign key
              env:
                  MINISIGN_PRIV_KEY: ${{ secrets.MINISIGN_PRIV_KEY }}
              run: |
                  printf '%s' "$MINISIGN_PRIV_KEY" > minisign.key
            - name: Sign DMG
              run: minisign -S -s minisign.key -m "hummingbird-$ARCH.dmg"
            - name: Sign Zip
              run: minisign -S -s minisign.key -m "hummingbird-$ARCH.zip"
            - uses: actions/upload-artifact@v4
              with:
                  name: hummingbird-${{ env.ARCH }}.dmg
                  path: |
                      hummingbird-${{ env.ARCH }}.dmg
                      hummingbird-${{ env.ARCH }}.dmg.minisig
            - uses: actions/upload-artifact@v4
              with:
                  name: hummingbird-${{ env.ARCH }}.zip
                  path: |
                      hummingbird-${{ env.ARCH }}.zip
                      hummingbird-${{ env.ARCH }}.zip.minisig
            - uses: softprops/action-gh-release@v2
              with:
                  files: |
                      hummingbird-${{ env.ARCH }}.dmg
                      hummingbird-${{ env.ARCH }}.dmg.minisig
                      hummingbird-${{ env.ARCH }}.zip
                      hummingbird-${{ env.ARCH }}.zip.minisig
                  name: ${{ github.event.release.name }}
                  tag_name: ${{ github.event.release.tag_name }}
